name: ExecuteQuery build test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.PostgreSQL.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@add-azure-artifacts-push
    with:
      workdir: Frends.PostgreSQL.ExecuteQuery
      prebuild_command: docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
