name: ExecuteQuery build main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.PostgreSQL.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.PostgreSQL.ExecuteQuery
      prebuild_command: docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}